[32m   INFO [35mtests.test_typical_u[39;49;0m CTX=test CTX_INT= Message #1[39;49;0m
[37m  DEBUG [35mtests.test_typical_u[39;49;0m CTX=test CTX_INT=method Message #2[39;49;0m
[31m  ERROR [35mtests.test_typical_u[39;49;0m CTX=test CTX_INT=method Exception
Traceback (most recent call last):
  File "%s", line 40, in method
    raise RuntimeError
RuntimeError

Locals at innermost frame:

{'__logger_context': {'ctx': 'test', 'ctx_internal': 'method'},
 'bar': 1,
 'log': %s,
 'saved_logger': [%s]}[39;49;0m
[32m   INFO [35mtests.test_typical_u[39;49;0m CTX=test CTX_INT= Message #3[39;49;0m
